### ISSUE TITLE
прошу проверить исправления и ответить на вопросы

### ISSUE THREAD

**Issue by Alanrus** [Alanrus/03-ClubProgram#4]
@coursar вопросы:
1. Когда я закрываю задачу Вам же приходит уведомление?
2. как сделать так, чтобы одним коммитом закрывалось сразу несколько задач? мне нужно было закрыть 2-3 и я ввел коммит "fixed #2 #3", но получилось закрыть только 2 задачу.

**Comment by coursar** [comment]
1. Да

**Comment by coursar** [comment]
2. fixes #2, fixes #3
